const THEORY=[
  {id:"bases",title:"Bases y Base Reguladora",icon:"📊",content:[
    {t:"sub",v:"¿Qué es la Base de Cotización (BC)?"},
    {t:"text",v:"Es la cantidad sobre la que se aplican los porcentajes de cotización para calcular lo que paga la empresa y el trabajador a la Seguridad Social cada mes. Se calcula a partir de la retribución mensual bruta del trabajador, incluyendo salario base, complementos salariales, pagas extra prorrateadas y, en su caso, horas extraordinarias."},
    {t:"formula",v:"BC mensual = Salario base + Complementos + Prorrata pagas extra"},
    {t:"tip",v:"La BC tiene topes: una base mínima y una base máxima que fija el Gobierno cada año. En 2026, la base máxima del Régimen General es de 5.101,20 €/mes (RD-ley 3/2026)."},
    {t:"sub",v:"Tipos de Base de Cotización"},
    {t:"table",h:["Tipo","¿Qué incluye?","¿Para qué se usa?"],r:[
      ["BCCC (Conting. Comunes)","Salario base + complementos + prorrata pagas extra (SIN horas extra)","Cotizaciones por CC, y la BR de IT por enf. común, nacimiento, jubilación…"],
      ["BCCP (Conting. Profesionales)","Todo lo anterior + horas extraordinarias","Cotizaciones por AT/EP, desempleo, FOGASA, FP, y la BR de IT por AT/EP y desempleo"],
    ]},
    {t:"tip",v:"Diferencia clave: las horas extraordinarias NO se incluyen en la BCCC pero SÍ en la BCCP."},
    {t:"sub",v:"Ejemplo numérico"},
    {t:"text",v:"Pablo, técnico de imagen diagnóstica: salario base 1.200 €, complemento turnicidad 200 €, prorrata pagas 233,33 €, horas extra 150 €."},
    {t:"formula",v:"BCCC = 1.200 + 200 + 233,33 = 1.633,33 € (sin horas extra)"},
    {t:"formula",v:"BCCP = 1.200 + 200 + 233,33 + 150 = 1.783,33 € (con horas extra)"},
    {t:"tip",v:"¿Por qué las horas extra van aparte? Porque son irregulares. Para contingencias comunes se busca una base estable. Para profesionales se incluye todo, porque un AT puede ocurrir precisamente haciendo horas extra."},
    {t:"sub",v:"¿Qué es la Base Reguladora (BR)?"},
    {t:"text",v:"Es la cantidad sobre la que se calcula la cuantía de una prestación (baja, desempleo, jubilación…). Se obtiene a partir de las BC, pero la fórmula varía según la prestación."},
    {t:"table",h:["Concepto","Base de Cotización","Base Reguladora"],r:[
      ["¿Qué es?","Cantidad sobre la que se cotiza cada mes","Cantidad sobre la que se calcula la prestación"],
      ["¿Cuándo se usa?","Cada mes, para calcular cotizaciones","Cuando nace el derecho a una prestación"],
      ["¿Quién la determina?","Se deriva del salario bruto","Se calcula con fórmulas específicas por prestación"],
      ["Ejemplo","Técnico cobra 1.800 € → BCCC = 1.800 €","Gripe → BR diaria = 1.800 ÷ 30 = 60 €/día"],
    ]},
    {t:"sub",v:"Fórmulas de BR por prestación"},
    {t:"table",h:["Prestación","Fórmula","Base"],r:[
      ["IT (enf. común)","BCCC mes anterior ÷ 30","BCCC"],
      ["IT (AT/EP)","(BCCP mes anterior ÷ 30) + (H. extra año ÷ 365)","BCCP"],
      ["Nacimiento","BCCC mes anterior ÷ 30","BCCC"],
      ["Desempleo","Suma BCCP últimos 180 días ÷ 180","BCCP"],
      ["Jubilación","Media BCCC últimos 25 años (÷ 350)","BCCC"],
    ]},
    {t:"tip",v:"Truco: la BC es lo que PAGAS (cotizaciones), la BR es lo que COBRAS (prestaciones). La BC alimenta la BR."},
  ]},
  {id:"regimenes",title:"Regímenes",icon:"🏛️",content:[
    {t:"text",v:"El sistema se articula en dos grandes bloques:"},
    {t:"table",h:["Régimen","¿A quién incluye?","Ejemplos"],r:[
      ["Régimen General","Trabajadores por cuenta ajena","Técnico de radioterapia en hospital, administrativos…"],
      ["Regímenes Especiales","Actividades con características especiales","Autónomos (RETA), Trabajadores del Mar, Minería del Carbón…"],
    ]},
    {t:"tip",v:"Como técnico/a sanitario/a en un hospital estarás en el Régimen General. Si abres tu propia clínica, en el RETA (autónomos)."},
  ]},
  {id:"entidades",title:"Entidades Gestoras",icon:"🏢",content:[
    {t:"table",h:["Entidad","Función principal"],r:[
      ["INSS","Prestaciones económicas contributivas: IT, jubilación, viudedad, orfandad, nacimiento…"],
      ["INGESA","Servicios sanitarios en Ceuta y Melilla"],
      ["IMSERSO","Prestaciones para mayores y personas con discapacidad"],
      ["ISM","Prestaciones de trabajadores del mar"],
      ["SEPE","Desempleo, formación e intermediación laboral"],
      ["INSST","Asesoramiento en prevención de riesgos laborales"],
    ]},
    {t:"tip",v:"Las Mutuas Colaboradoras gestionan AT/EP e IT. Cada empresa elige su Mutua al inscribirse."},
  ]},
  {id:"obligaciones",title:"Obligaciones Empresa",icon:"📋",content:[
    {t:"sub",v:"1. Inscripción"},
    {t:"text",v:"La empresa solicita inscripción ante la TGSS y recibe un CCC (Código de Cuenta de Cotización) de 11 cifras. Necesita un CCC por cada provincia donde tenga centro de trabajo."},
    {t:"sub",v:"2. Afiliación, Alta y Baja"},
    {t:"table",h:["Acto","Descripción","Plazo"],r:[
      ["Afiliación","Una sola vez en la vida. Se asigna NAF.","Antes de la 1ª relación laboral"],
      ["Alta","Cada nueva relación laboral","Antes de comenzar (hasta 60 días antes)"],
      ["Baja","Al finalizar la relación laboral","3 días naturales"],
    ]},
    {t:"tip",v:"Si el empresario no da el alta → «alta presunta»: el trabajador mantiene derechos pero el empresario responde directamente."},
    {t:"sub",v:"3. Cotización — Régimen General 2026"},
    {t:"table",h:["Concepto","Empresa","Trabajador","Total"],r:[
      ["Contingencias comunes","23,60 %","4,70 %","28,30 %"],
      ["Desempleo (indefinido)","5,50 %","1,55 %","7,05 %"],
      ["Desempleo (temporal)","6,70 %","1,60 %","8,30 %"],
      ["FOGASA","0,20 %","—","0,20 %"],
      ["Formación profesional","0,60 %","0,10 %","0,70 %"],
      ["MEI","0,75 %","0,15 %","0,90 %"],
    ]},
    {t:"tip",v:"La empresa paga aprox. 30–32 % y el trabajador 6,35–6,45 %. La empresa paga unas 5 veces más."},
  ]},
  {id:"autonomos",title:"Autónomos",icon:"💼",content:[
    {t:"text",v:"Los autónomos (RETA) cotizan según rendimientos netos reales."},
    {t:"table",h:["Concepto","Tipo","Cobertura"],r:[
      ["Contingencias comunes","28,30 %","Jubilación, IT, IP, muerte y supervivencia"],
      ["Contingencias profesionales","1,30 %","AT y EP"],
      ["Cese de actividad","0,90 %","Equivalente a desempleo"],
      ["Formación profesional","0,10 %","Formación continua"],
      ["MEI","0,90 %","Sostenibilidad pensiones"],
    ]},
    {t:"sub",v:"Tarifa plana 2026"},
    {t:"text",v:"80 €/mes (≈ 88,72 € con MEI al 0,90 %) durante 12 meses. Prorrogable 12 meses más si rendimientos < SMI. Colectivos especiales (discapacidad, violencia de género, terrorismo): 24 meses, prorrogables 36 más si rendimientos < SMI."},
  ]},
  {id:"it",title:"Incapacidad Temporal",icon:"🩺",content:[
    {t:"text",v:"Situación en la que un trabajador temporalmente no puede trabajar y necesita asistencia sanitaria."},
    {t:"sub",v:"Requisitos"},
    {t:"text",v:"Afiliado y en alta. Enfermedad común: 180 días cotizados en los últimos 5 años. AT, EP o accidente no laboral: no se exige período previo."},
    {t:"sub",v:"Duración: máx. 12 meses + 6 de prórroga"},
    {t:"sub",v:"Enfermedad común / Acc. no laboral"},
    {t:"table",h:["Días","% de la BR","¿Quién paga?"],r:[
      ["Días 1-3","0 % (no se cobra)","Nadie"],
      ["Días 4-15","60 %","Empresario"],
      ["Días 16-20","60 %","INSS / Mutua"],
      ["Día 21 en adelante","75 %","INSS / Mutua"],
    ]},
    {t:"sub",v:"AT / EP"},
    {t:"table",h:["Días","% de la BR","¿Quién paga?"],r:[
      ["Día de la baja","Salario íntegro","Empresario"],
      ["Día siguiente en adelante","75 %","Mutua / INSS"],
    ]},
    {t:"sub",v:"Cálculo de la BR diaria"},
    {t:"formula",v:"Enf. común → BR = Base CC mes anterior ÷ 30"},
    {t:"formula",v:"AT/EP → BR = (BCCP mes anterior ÷ 30) + (H. extra año anterior ÷ 365)"},
  ]},
  {id:"nacimiento",title:"Nacimiento",icon:"👶",content:[
    {t:"text",v:"Prestación por suspensión del contrato: maternidad biológica, adopción o acogimiento."},
    {t:"sub",v:"16 semanas por progenitor (individual e intransferible)"},
    {t:"text",v:"6 primeras obligatorias e ininterrumpidas. 10 restantes a tiempo completo o parcial. +2 semanas por cada hijo a partir del segundo."},
    {t:"sub",v:"Carencia según edad"},
    {t:"table",h:["Edad","Cotización mínima"],r:[
      ["< 21 años","No se exige"],
      ["21-26 años","90 d. en últimos 7 años o 180 d. en toda la vida"],
      ["> 26 años","180 d. en últimos 7 años o 360 d. en toda la vida"],
    ]},
    {t:"tip",v:"Cuantía: 100 % de la BR = Base CC mes anterior ÷ 30."},
  ]},
  {id:"ip",title:"Incapacidad Permanente",icon:"♿",content:[
    {t:"table",h:["Grado","Definición","Cuantía"],r:[
      ["IP Parcial","≥ 33 % disminución en profesión habitual","24 mensualidades de la BR"],
      ["IP Total","No puede ejercer su profesión habitual","55 % BR (75 % si ≥ 55 sin empleo)"],
      ["IP Absoluta","Incapaz para cualquier profesión","100 % de la BR"],
      ["Gran Invalidez","Necesita asistencia para actos esenciales","100 % BR + complemento"],
    ]},
    {t:"sub",v:"Carencia (enfermedad común)"},
    {t:"text",v:"IP Parcial: 1.800 días en últimos 10 años. IP Total/Absoluta/GI: < 31 años → 1/3 desde los 16. ≥ 31 años → 1/4 desde los 20 (mín. 5 años), con 1/5 en últimos 10 años."},
    {t:"tip",v:"Si la causa es AT, EP o accidente no laboral → NO se exige cotización previa."},
  ]},
  {id:"jubilacion",title:"Jubilación",icon:"☀️",content:[
    {t:"sub",v:"Requisitos 2026"},
    {t:"text",v:"Edad: 66 años y 10 meses (general), o 65 años con ≥ 38 años y 3 meses cotizados. Cotización mínima: 15 años (2 en los últimos 15). Cese de actividad. En 2027 la edad general llegará a 67 años (≥ 38 años y 6 meses para mantener los 65)."},
    {t:"sub",v:"Cálculo de la BR (sistema dual 2026–2040)"},
    {t:"formula",v:"Fórmula A → BR = Bases de 300 meses (25 años) anteriores ÷ 350"},
    {t:"formula",v:"Fórmula B → BR = 302 bases más altas de últimos 304 meses ÷ 352,33"},
    {t:"text",v:"Se aplica la más beneficiosa. Últimos 24 meses a valor nominal, anteriores con IPC. Porcentaje: 50 % (15 años) → 100 % (36 años y 6 meses)."},
    {t:"tip",v:"Complemento brecha de género 2026: 36,90 €/mes por hijo/a (máx. 4 hijos). Revalorizado un 2,7 % respecto a 2025 (RD-ley 3/2026)."},
  ]},
  {id:"desempleo",title:"Desempleo",icon:"📉",content:[
    {t:"sub",v:"Requisitos"},
    {t:"text",v:"Afiliado y en alta. ≥ 360 días cotizados en últimos 6 años. No haber alcanzado edad de jubilación. Situación legal de desempleo (NO dimisión)."},
    {t:"sub",v:"Cuantía (art. 270 LGSS)"},
    {t:"table",h:["Período","Cuantía"],r:[
      ["Primeros 180 días","70 % de la BR"],
      ["Desde el día 181","60 % de la BR"],
    ]},
    {t:"formula",v:"BR = Suma bases CP últimos 180 días ÷ 180"},
    {t:"sub",v:"Duración según cotización"},
    {t:"table",h:["Días cotizados","Días de prestación"],r:[
      ["360-539","120"],["540-719","180"],["720-899","210"],["900-1.079","240"],
      ["1.080-1.259","300"],["1.260-1.439","330"],["1.440-1.619","360"],
      ["1.620-1.799","420"],["1.800-1.979","480"],["1.980-2.159","540"],["2.160 +","720"],
    ]},
    {t:"tip",v:"Plazo para solicitar: 15 días hábiles. Capitalización (pago único): ≥ 3 meses pendientes, no usado en 4 años, solicitar antes de iniciar actividad como autónomo."},
  ]},
];
